monitorHosts:
  host17:
    address: tcp://192.168.56.101:2375
    apiVersion: 1.26
intervalTime: 5s
monitorTime: 20h
monitorSwitch: false
##当监控的容器挂掉的时候，将会通过邮件通知
mailNotice:
  mailUser: lilei@yunphant.com
  mailPasswd: 8WDSaWvjehE5zRek
  smtpHost: smtp.exmail.qq.com:587
  receiveMail:
    - lilei@yunphant.com
    - 728129018@qq.com